import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavigationSidebar from "../components/NavigationSidebar";
import dimHome from "@/../public/dimHome.svg";
import dimBell from "@/../public/dimBell.svg";
import dimHelp from "@/../public/dimHelp.svg";
import Apps from "@/../public/apps.svg";
import OdrHistory from "@/../public/odrHistory.svg";
import SideBar from "../components/Sidebar";
import bookers from "@/../public/bookers.svg"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>

				<NavigationSidebar
					icon={[
						dimHome,
						Apps,
						dimBell,
						OdrHistory,
						dimHelp,
					]}
					main={children}
					Children={
						<>
						<SideBar
					img={bookers}
					tab={"Bookers"}
					changeState={'/'}
				/>
						</>
					}
				/>
			</body>
		</html>
	);
}
