import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavigationSidebar from "../components/NavigationSidebar";
import dimHome from "@/../public/dimHome.svg";
import dimBell from "@/../public/dimBell.svg";
import dimHelp from "@/../public/dimHelp.svg";
import Apps from "@/../public/apps.svg";
// import { GlobalStateProvider } from "./components/globalVariable";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				{/* <GlobalStateProvider>{children}</GlobalStateProvider> */}
				
				<NavigationSidebar
				icon={[dimHome, Apps, dimBell, dimHelp]}
				main={
					children
				}
			/>
				
			</body>
		</html>
	);
}
