
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavigationSidebar from "../components/NavigationSidebar";
import dimHome from "@/../public/dimHome.svg";
import dimBell from "@/../public/dimBell.svg";
import dimHelp from "@/../public/dimHelp.svg";
import deals from "@/../public/apps.svg";
import OdrHistory from "@/../public/odrHistory.svg";
// import SideBar from "../components/Sidebar";
// import { ToastContainer } from "react-toastify";
// import { GlobalStateProvider } from "./components/globalVariable";
import { CiUser } from "react-icons/ci";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NavigationSidebar
					icon={[
						dimHome,
						dimBell,
						dimHelp,
					]}
					main={children}
					thirdSection={{
						image: deals,
						name: "Deals",
						changeState: "/deals"
					}} fourthSection={{
						image: OdrHistory,
						name: "Order History",
						changeState: "/odrHistory"
					}}
					fifthSection={{
						image: <CiUser className="w-[26px] h-[26px] min-w-[30px] min-h-7"/>,
						name: "Profile",
						changeState: "/userProfile"
					}} firstSection={"/dashboard"} secondSection={"/dashboard"}/>
			</body>
		</html>
	);
}
